### PR TITLE
Fix samd TX pin config, fix #35

### LINKED ISSUE #35: [BUG] SAMD21 board don't high impedance TX pin when TX is disabled
**Describe the bug**
SAMD21 board don't high impedance TX pin when TX is disabled

This bug has been spotted by @XRobots .

**Network configuration**
More than 2 boards in a one-wire configuration (2 still work). 

**Additional context**
When one of the board try to send something the 0 state is not 0 because the other board pulls it to 1. The more board you put on the network the more shitty your signal will be.
We have to switch TX in high impedance when it's disabled.

### PR DESCRIPTION
**Pull request by nicolas-rabault**
🛠️ Fix: SAMD21 board don't high impedance TX pin when TX is disabled #35 

<br><br />
<br><br />
               *!!! WARNING : DO NOT EDIT THE CHECKLIST BELOW !!!*
# Checklist : Merge from DEVELOP branch
## Code Quality
- [x] Each function has a header (description, inputs, outputs) 
- [x] Code is commented (particularly in hard to understand areas)
- [x] There are no new warnings that can be corrected
- [x] Commits policy is respected (constitancy commits, clear commits comments)
<br><br />
## Tests Review
- [x]  Manual Tests for new features have been *reviewed*
- [x]  Automatic Tests for new features have been *reviewed*
<br><br />
## Tests are passed the best as I can
- [x]  Non regression existing tests are *passed OK*
- [x]  New tests for new features & bug fixes are *passed OK*
<br><br />
## Documentation
- [x] Documentation is up to date
- [x] Changelog for next release is up-to-date : [fill here](https://github.com/Luos-io/Luos/pull/115)
- [x] If needed, tests are briefly described in [test repository](https://github.com/Luos-io/tests)

### CODE REVIEW

**Comment by nicolas-rabault** [comment]
@Salem-Luos I have not tested the non-Arduino configuration.
Can you check my code and test it for me, please?

File: ATSAMD21_ARDUINO/luos_hal.c [hunk 1]
```diff
@@ -551,8 +554,6 @@ static void LuosHAL_GPIOInit(void)
 
     /*Configure GPIO pin : TxPin */
     PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN].reg = PORT_PINCFG_RESETVALUE;                    // no pin mux / no input /  no pull / low streght
-    PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN].reg |= PORT_PINCFG_PMUXEN;                       // mux en
-    PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN].reg |= PORT_PINCFG_PULLEN;                       // Tx open drain
```
Comment (Salem-Tho) [inline ATSAMD21_ARDUINO/luos_hal.c:555]: you need to set up the disable config at init with : 
        PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN] = PORT_PINCFG_RESETVALUE_Msk; // no pin mux / no input /  no pull / low streght
        PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN] |= PORT_PINCFG_PULLEN_Msk;    // Enable Pull
        PORT->Group[COM_TX_PORT].OUTSET = (1 << COM_TX_PIN);                      // Pull up

File: ATSAMD21/luos_hal.c [hunk 2]
```diff
@@ -563,9 +566,7 @@ static void LuosHAL_GPIOInit(void)
     }
 
     /*Configure GPIO pin : TxPin */
-    PORT_REGS->GROUP[COM_TX_PORT].PORT_PINCFG[COM_TX_PIN] = PORT_PINCFG_RESETVALUE; // no pin mux / no input /  no pull / low streght
-    PORT_REGS->GROUP[COM_TX_PORT].PORT_PINCFG[COM_TX_PIN] |= PORT_PINCFG_PULLEN_Msk;
-    PORT_REGS->GROUP[COM_TX_PORT].PORT_PINCFG[COM_TX_PIN] |= PORT_PINCFG_PMUXEN_Msk;                   // mux en
+    PORT_REGS->GROUP[COM_TX_PORT].PORT_PINCFG[COM_TX_PIN] = PORT_PINCFG_RESETVALUE;                    // no pin mux / no input /  no pull / low streght
```
Comment (Salem-Tho) [inline ATSAMD21/luos_hal.c:569]: you need to set up the disable config au init with : 
        PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN].reg = PORT_PINCFG_RESETVALUE; // no pin mux / no input /  no pull / low streght
        PORT->Group[COM_TX_PORT].PINCFG[COM_TX_PIN].reg |= PORT_PINCFG_PULLEN;    // Enable Pull
        PORT->Group[COM_TX_PORT].OUTSET.reg = (1 << COM_TX_PIN);                  // Pull up

**Review by Salem-Tho — CHANGES_REQUESTED** [review]

**Review by Salem-Tho — APPROVED** [review]

**Review by JeromeGalan — APPROVED** [review]
